language: python
dist: trusty

services:
  - docker

before_install:
  - docker build --rm -t jumpscale .

script:
  - docker run --rm -t jumpscale /bin/bash -c "source /sandbox/env.sh; pytest -v /sandbox/code/github/threefoldtech/jumpscaleX"

after_success:
  - docker run --rm -t jumpscale /bin/bash -c "codecov"