[startup.etcd]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed

[startup.etcd.args]
script = """
echo '''name: "etcd_builder"
data-dir: "/mnt/data"
listen-peer-urls: "http://0.0.0.0:2380"
listen-client-urls: "http://0.0.0.0:2379"
initial-advertise-peer-urls: "http://'$node_addr':2380"''' > etcd.conf

/sandbox/bin/etcdctl  user add root:$etcd_password
/sandbox/bin/etcdctl  auth enable
/sandbox/bin/etcdctl  --user=root:$etcd_password put "traefik/acme/account" "foo"
/sandbox/bin/etcd --config-file etcd.conf
"""