[startup.coredns]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed

[startup.coredns.args]
script = """
echo '''. {
    etcd $domain {
        stubzones
        path /hosts
        endpoint $etcd_endpoint
        fallthrough
        debug
    }
    loadbalance
    redis {
        address ADDR
        password PWD
        prefix PREFIX
        suffix SUFFIX
        connect_timeout TIMEOUT
        read_timeout TIMEOUT
        ttl TTL
    }
    reload 5s
}''' > coredns.conf

/sandbox/bin/coredns -conf coredns.conf
"""