[startup.mysql]
name = "core.system"
after = ["setup"]
protected = true

[startup.mysql.args]
name = "mysqld"

[startup.apache]
name = "core.system"
protected = true
after = ["setup"]

[startup.apache.args]
name = "apachectl"
args = [
    "-DFOREGROUND"
]

[startup.cron1]
name = "bash"
recurring_period = 60

[startup.cron1.args]
script = """
/usr/bin/php /var/www/html/humhub/protected/yii queue/run >/dev/null 2>&
"""

[startup.cron2]
name = "bash"
recurring_period=60

[startup.cron2.args]
script = """
/usr/bin/php /var/www/html/humhub/protected/yii cron/run >/dev/null 2>&1
"""

[startup.setup]
name = "bash"
running_delay = -1

[startup.setup.args]
script = """
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
export HOME=/root
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
chmod -R 775 /var/www/

chmod 400 -R /etc/ssh/
chown -R www-data:www-data /var/www/

chown -R mysql /var/lib/mysql/
chown -R mysql /var/log/mysql/
chown -R mysql /var/run/mysqld/
"""
