[startup.hub]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed

[startup.hub.args]
script = """
sed -i "s/\\"zflist-bin\\": \\"\/opt\/0-flist\/zflist\/zflist\\"/\\"zflist-bin\\":\
\\"\/sandbox\/zeroflist\/zflist\/zflist\\"/" /sandbox/hub/python/config.py
pip3 install -r /sandbox/hub/requirements.txt;
tmux new-session -d -s 0-db '/sandbox/bin/zdb';
tmux new-session -d -s hub '/sandbox/hub/python/ && python3 flist-uploader.py';
"""